version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION:-8.1}
      dockerfile: ./docker/php/Dockerfile
    working_dir: /symfony_app
    user: ${UID:-1000}:${GID:-1000}
    restart: unless-stopped
    volumes:
      - ./:/symfony_app
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - db
    container_name: symf_app_php

  db:
    image: "postgres:${POSTGRES_VERSION:-14}"
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db_data
    container_name: symf_db
    environment:
      POSTGRES_PASSWORD: project
      POSTGRES_USER: project
      POSTGRES_DB: project

  web:
    image: "nginx:${NGINX_VERSION:-1.21}"
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./assetsv2/dist:/symfony_app
      - ./docker/nginx/:/etc/nginx/conf.d
    container_name: symf_nginx

  node:
    image: "node:${NODE_VERSION:-18}"
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./assetsv2:/assets
    working_dir: /assets
    container_name: symf_node
    command: sh -c "yarn install && yarn serve"
    expose:
      - "8080"
    environment:
      NODE_ENV: development
      HOME: /assets
      YARN_CACHE_FOLDER: /tmp/yarn

volumes:
  db_data: